# 名称
name: tracker-merge

# 触发条件
on:
  # 手动运行
  workflow_dispatch:
  # 推送触发
  push:
    branches:
      - main
  # 定时运行
  schedule:
    # 每天运行一次
    - cron: '30 05 * * *'


jobs:
  ssl-push:
    # 合并多个tracker资源 push github
    name: tracker merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: merge-best
        shell: bash
        run: |
          # 获取链接的文本内容，并合并成一个文件
          curl -s https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt \
                  https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_best.txt \
                  https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/best.txt \
                  | cat > best_temp.txt
          # 对文件进行去重和排序，并去除空行
          sort -u best_temp.txt | uniq | sed '/^$/d' > best.txt
          # 删除临时文件
          rm best_temp.txt
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}

      - name: merge-all
        shell: bash
        run: |
          # 获取链接的文本内容，并合并成一个文件
          curl -s https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt \
                  https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt \
                  https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt \
                  | cat > all_temp.txt
          # 对文件进行去重和排序，并去除空行
          sort -u all_temp.txt | uniq | sed '/^$/d' > all.txt
          # 删除临时文件
          rm all_temp.txt
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}

      - name: Commit
        run: |
          git config --global user.name "github推送"
          git config --global user.email "me@itwmb.com"

          git add .
          git commit -m "Upload on $(date +"%Y-%m-%d %H:%M:%S")"
          git push
        env:
          TZ: Asia/Shanghai

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}